companies:
  - name: 国家电网
    aliases:
      - 国家电网有限公司
      - 国家电网公司
      - 国网
      - State Grid
  - name: 南方电网
    aliases:
      - 中国南方电网有限责任公司
      - 南方电网公司
      - 南网
      - China Southern Power Grid
      - CSG
  - name: 国家能源集团
    aliases:
      - 国家能源投资集团有限责任公司
      - 中国神华
      - 国能
      - China Energy

